version: '3'
services:
  makara:
    image: vandeth_nextjs:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3224:3000
    networks:
      - data_analytics
networks:
  data_analytics:
    external: true 