version: '3'
services:
  vandeth:
    image: panda_ecommerce:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3224:3000
    networks:
      - data_analytics
networks:
  data_analytics:
    external: true 